/* Shared image URLs and site data */
const IMG = {
  sigiriya: 'https://images.unsplash.com/photo-1612862862126-865765df2ded?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1400&q=80',
  sigiriyaAerial: 'https://images.unsplash.com/photo-1711797750174-c3750dd9d7c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1400&q=80',
  beach: 'https://images.unsplash.com/photo-1519566335946-e6f65f0f4fdf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1400&q=80',
  beach1: 'https://res.klook.com/image/upload/w_750,h_469,c_fill,q_85/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/ep29e5zs0fadacjhqabp.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1400&q=80',
  beach2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl0WnfXVttFRy8fgXvE3ID4SS6YzMBaxTXQZbLR70MXdp8lHLDc6Lj1dA&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  tea1: 'https://lakpura.com/cdn/shop/files/LK951R0000-10-E_4fb5ce5e-c060-481b-9ee3-429c7a3a7b72.jpg?v=1689939550&width=3840?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  tea2: 'https://images.unsplash.com/photo-1544015759-237f87d55ef3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1400&q=80',
  waterfall: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBp0I-ITD07Sckl1aZQ6a7JeC95N7Ccij7u42UM_DcnQ&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  adamspeak: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT10DAeA9CGIdJnViv4WwG6PXRSFfdhohr6OnDEIksSEQ&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  cliff: 'https://off2srilanka.com/wp-content/uploads/2025/01/Horton-Plains-national-park-Sri-Lanka.png?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  train: 'https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  train2: 'https://images.unsplash.com/photo-1578519050142-afb511e518de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  bear: ' https://idubephotosafaris.com/wp-content/uploads/2023/06/0F9A2486-CR3_DxO_DeepPRIME.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  elephant: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSztfxr5A50iiIODthYniSr22WFnyJEFS1bpRJuv4Qv1yKEbkLezejgxZU&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  elephant2: 'https://images.unsplash.com/photo-1581852017103-68ac65514cf7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  bird: 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/22/52/ea.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  leopard: 'https://cdn.kimkim.com/files/a/images/db5406f4f727010e02337b2f1e4cf185ada16925/original-6aaf973fc9751a25bcef239a0753d10c.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  turtle: 'https://i.pinimg.com/736x/04/1d/92/041d9229313afa908aecfc5652fcf589.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  galle: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQkYFofAi4_M5HLnHyNLR6ciNJ3GuVdGA5dB0o-RmmIDyRK4W5R1R00hKR&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  jetwing:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/490937419.jpg?k=db375a7f6605f58e61e5c215e67b123fb574b467d15a784387c7b2b04cc272c0&o=?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1400&q=80',
  shangrila: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/295690509.jpg?k=01595718077c282ae900b6932c3be1243556845789d57de946a4907885349ceb&o=?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  cinnamon: 'https://d18slle4wlf9ku.cloudfront.net/www.cinnamonhotels.com-1754953340/cms/cache/v2/68f5c52a52e3c.jpg/392x392/fit/80/60b5e7eea70a8fb1280c97f9698ae019.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  heritance: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1jZul-RgLSBNooQ5WdiiTkqNIa3qncmr1waS3c4si0rZmaa-7hwHNqIC6&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  amaya: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQAzNXGAVmwJdxATpvl8TDNjyWxERbvW2cDdJYLvTOn3KVJgI9K8Uvua7G&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  bentota: 'https://d3prz3jkfh1dmo.cloudfront.net/sites/3/2025/10/villa-ben-gallery-exterior-lg-feat-3.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  kandy: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiomhJ9TfkH_3BCzdDyA4bsKCQ8Qg-I18hWk5dwf9yCRF92vdqbqpvEDM&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  food: 'https://i.pinimg.com/1200x/50/ec/be/50ecbece7862999cba5d697c7656b955.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  rice: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMDIlQLotBYLSMXb50FU_c_tqdasQmPbOs2e0Llkyg6OCIYPGmB6UYZbQ&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  traditional: 'https://pureceylonitems.com/wp-content/uploads/2024/02/Aluth-Avurudu-Sweets.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  pkgCultural: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS39AJ5z90nrQNOdc3kZscd8IyBDT_tUsyH7fnD1bS2xg&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  pkgAdventure: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwjU8QeE-fAThoo133geDJt9qNYj6wqSS3CpuQJY9EBg&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  pkgHoneymoon: 'https://nynehotels.com/wp-content/uploads/2025/06/Top-5-Reasons-to-Choose-Sri-Lanka-for-your-Honeymoon-1200x630-1.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  pkgBeach: 'https://images.unsplash.com/photo-1603477849227-705c424d1d80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  pkgSafari: 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/08/39/6e/5b.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  pkgHillCountry: 'https://images.unsplash.com/photo-1658051161493-1d311c4c7b4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  batik: 'https://elsalenthal.com/wp-content/uploads/2025/04/femme-indonesie-batik.png?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  surf: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/2d/6e/80/arugam-bay-is-one-of.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  woodCarving: 'https://i.pinimg.com/1200x/93/f1/52/93f152349d4a8da2e79a0c1462db04a2.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  vesak: 'https://images.unsplash.com/photo-1717216229791-0d437312799a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  perahera: 'https://ik.imagekit.io/TBR/Island%20Events/Kandy%20Esala%20Perahera%20(Festival%20of%20the%20Tooth)%20Sri%20lanka.webp?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  backpack: 'https://assets.roar.media/Life/2016/08/cover-image-e1470286833146.jpg??crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  hidden: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9R7RNIIXgTKLfxeeGNaqMtfTMpVsocHjFsqU3LoI4fg&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  photography: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWxL35bxrTsRveOoQEtODJuv__GE0x_Zu2ihd2hjgZR8wotNKMfN8Q3Kg&s=10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  solo: 'https://www.lovesrilanka.org/wp-content/uploads/2020/06/LS_B3_Travelling-solo-A-girl_s-guide-to-travelling-to-sl_800x520.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  family: 'https://travellersisle.com/wp-content/uploads/2022/02/Sri-Lanka-with-toddlers-2.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
  budget: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/806119802.jpg?k=3ac521b911b1cd5b4ea34b764532bd243810bd477632343f8d3c933b6294596e&o=?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80',
};

const NAV_LINKS = [
  { label: 'Home', href: 'index.html', page: 'home' },
  { label: 'About', href: 'pages/about.html', page: 'about' },
  { label: 'Destinations', href: 'pages/destinations.html', page: 'destinations' },
  { label: 'Packages', href: 'pages/packages.html', page: 'packages' },
  { label: 'Hotels', href: 'pages/hotels.html', page: 'hotels' },
  { label: 'Food & Culture', href: 'pages/food-culture.html', page: 'food' },
  { label: 'Gallery', href: 'pages/gallery.html', page: 'gallery' },
  { label: 'Blog', href: 'pages/blog.html', page: 'blog' },
  { label: 'Contact', href: 'pages/contact.html', page: 'contact' },
];

const DESTINATIONS = [
  { name: 'Sigiriya', cat: 'Historical', rating: 4.9, season: 'Dec–May', desc: '5th-century rock fortress, UNESCO site with ancient frescoes and mirror wall.', budget: '$25 entry', img: IMG.sigiriyaAerial, things: ['Rock climb', 'Ancient frescoes', 'Sigiri village'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Sigiriya+Sri+Lanka' },
  { name: 'Ella', cat: 'Mountain', rating: 4.8, season: 'Year-round', desc: 'Misty highland village famed for Nine Arch Bridge, Little Adam\'s Peak and local cuisine.', budget: '$30–80/day', img: IMG.train, things: ['Nine Arch Bridge', 'Little Adam\'s Peak', 'Tea factory tours'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Ella+Sri+Lanka' },
  { name: 'Mirissa', cat: 'Beach', rating: 4.7, season: 'Nov–Apr', desc: 'Golden crescent beach, legendary whale watching and laid-back surf lifestyle.', budget: '$40–100/day', img: IMG.beach1, things: ['Whale watching', 'Surfing', 'Sunset cocktails'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mirissa+Sri+Lanka' },
  { name: 'Yala National Park', cat: 'Wildlife', rating: 4.8, season: 'Feb–Jul', desc: 'World\'s highest leopard density. Home to elephants, crocodiles and 200+ bird species.', budget: '$50 safari', img: IMG.elephant, things: ['Leopard safari', 'Bird watching', 'Elephant herds'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Yala+National+Park+Sri+Lanka' },
  { name: 'Galle Fort', cat: 'Historical', rating: 4.6, season: 'Dec–Apr', desc: 'UNESCO-listed 17th century Dutch fort with colonial streets, boutique shops and cafés.', budget: '$20–60/day', img: IMG.galle, things: ['Fort walk', 'Lighthouse', 'Boutique shopping'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Galle+Fort+Sri+Lanka' },
  { name: 'Nuwara Eliya', cat: 'Mountain', rating: 4.7, season: 'Jan–Apr', desc: 'Sri Lanka\'s Little England — lush tea estates, colonial bungalows and cool highland air.', budget: '$35–90/day', img: IMG.tea1, things: ['Tea factory visit', 'Gregory Lake', 'Horton Plains'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Nuwara+Eliya+Sri+Lanka' },
  { name: 'Arugam Bay', cat: 'Beach', rating: 4.6, season: 'May–Oct', desc: 'World-class surf point on the east coast with a relaxed beach village atmosphere.', budget: '$30–70/day', img: IMG.surf, things: ['Surfing', 'Crocodile safari', 'Pottuvil lagoon'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Arugam+Bay+Sri+Lanka' },
  { name: 'Horton Plains', cat: 'Adventure', rating: 4.7, season: 'Year-round', desc: 'Dramatic highland plateau with World\'s End cliff dropping 870 metres into jungle valley.', budget: '$25 entry', img: IMG.cliff, things: ['World\'s End hike', 'Baker\'s Falls', 'Cloud forest walk'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Horton+Plains+Sri+Lanka' },
  { name: 'Trincomalee', cat: 'Beach', rating: 4.5, season: 'May–Oct', desc: 'Stunning natural harbour with turquoise waters, whale sharks, hot springs and Hindu temples.', budget: '$35–80/day', img: IMG.beach, things: ['Nilaveli beach', 'Whale shark diving', 'Hot springs'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Trincomalee+Sri+Lanka' },
  { name: 'Kandy', cat: 'Religious', rating: 4.8, season: 'Year-round', desc: 'Cultural capital with the sacred Temple of the Tooth, Kandy Lake and Esala Perahera festival.', budget: '$25–70/day', img: IMG.kandy, things: ['Temple of Tooth', 'Peradeniya Botanic Gardens', 'Kandy cultural show'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Kandy+Sri+Lanka' },
  { name: 'Adam\'s Peak', cat: 'Adventure', rating: 4.8, season: 'Dec–May', desc: 'Sacred pilgrimage mountain climbed by all religions. The sunrise summit view is transcendent.', budget: '$15–30', img: IMG.adamspeak, things: ['Summit sunrise hike', 'Waterfall trails', 'Tea stalls'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Adams+Peak+Sri+Lanka' },
  { name: 'Bentota', cat: 'Beach', rating: 4.6, season: 'Nov–Apr', desc: 'Luxury beach resort town on the west coast — water sports, river safaris and turtle hatcheries.', budget: '$50–200/day', img: IMG.beach2, things: ['Jet skiing', 'River safari', 'Turtle hatchery'], mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bentota+Sri+Lanka' },
];

const PACKAGES = [
  { name: '5-Day Cultural Triangle', days: 5, price: '$350', tier: 'Budget', color: '#2D6A4F', img: IMG.pkgCultural, destinations: ['Colombo', 'Sigiriya', 'Dambulla', 'Polonnaruwa'], transport: 'Private Van', meals: 'B&B', accommodation: '3-star hotel', difficulty: 'Easy', desc: 'Discover the ancient Cultural Triangle — Sigiriya, Dambulla and Polonnaruwa in five packed days.' },
  { name: '7-Day Adventure Tour', days: 7, price: '$620', tier: 'Standard', color: '#0077B6', img: IMG.pkgAdventure, destinations: ['Ella', 'Adam\'s Peak', 'Kitulgala', 'Arugam Bay'], transport: 'Train + Van', meals: 'Half Board', accommodation: 'Boutique guesthouses', difficulty: 'Moderate', desc: 'Hike, raft, surf and explore — the ultimate active adventure through Sri Lanka\'s highlands and east coast.' },
  { name: 'Luxury Honeymoon', days: 10, price: '$2,800', tier: 'Luxury', color: '#F77F00', img: IMG.pkgHoneymoon, destinations: ['Bentota', 'Galle', 'Nuwara Eliya', 'Mirissa'], transport: 'Private Chauffeur', meals: 'Full Board', accommodation: '5-star beach villa', difficulty: 'Easy', desc: 'A romantic island escape — pristine beaches, hill country and candlelit dinners by the Indian Ocean.' },
  { name: 'Beach Escape', days: 6, price: '$480', tier: 'Standard', color: '#0077B6', img: IMG.pkgBeach, destinations: ['Negombo', 'Bentota', 'Unawatuna', 'Mirissa'], transport: 'Private Van', meals: 'B&B', accommodation: 'Beach resort', difficulty: 'Easy', desc: 'A coastal journey along Sri Lanka\'s stunning shoreline with crystal clear waters and white sand beaches.' },
  { name: 'Wildlife Safari', days: 5, price: '$540', tier: 'Standard', color: '#2D6A4F', img: IMG.pkgSafari, destinations: ['Yala', 'Udawalawe', 'Minneriya', 'Wilpattu'], transport: '4x4 Safari Jeep', meals: 'Half Board', accommodation: 'Eco-lodge', difficulty: 'Easy', desc: 'Sri Lanka\'s legendary wildlife — leopards, elephants and exotic birds across four national parks.' },
  { name: 'Hill Country Tour', days: 6, price: '$420', tier: 'Budget', color: '#2D6A4F', img: IMG.pkgHillCountry, destinations: ['Kandy', 'Nuwara Eliya', 'Ella', 'Horton Plains'], transport: 'Train + Tuk-tuk', meals: 'B&B', accommodation: 'Tea estate bungalows', difficulty: 'Moderate', desc: 'Ride the famous hill country train through emerald tea estates and explore misty mountain villages.' },
];

const HOTELS = [
  { name: 'Shangri-La Hambantota', stars: 5, tier: 'Luxury', price: '$320/night', location: 'Colombo', desc: 'Iconic 5-star tower overlooking the Indian Ocean with world-class dining and spa facilities.', facilities: ['Pool', 'Spa', '5 Restaurants', 'Gym', 'Ocean view'], img: IMG.shangrila},
  { name: 'Jetwing Lighthouse', stars: 5, tier: 'Luxury', price: '$280/night', location: 'Galle', desc: 'Geoffrey Bawa-designed masterpiece on a rocky headland — art, architecture and ocean panoramas.', facilities: ['Infinity Pool', 'Spa', 'Fine Dining', 'Sunset Terrace'], img: IMG.jetwing },
  { name: 'Cinnamon Wild Yala', stars: 4, tier: 'Resort', price: '$180/night', location: 'Yala', desc: 'Award-winning eco-resort bordering Yala National Park. Fall asleep to sounds of the wild.', facilities: ['Safari Jeeps', 'Pool', 'Wildlife Deck', 'Jungle Dining'], img: IMG.cinnamon},
  { name: 'Heritance Tea Factory', stars: 4, tier: 'Boutique', price: '$220/night', location: 'Nuwara Eliya', desc: 'A converted Victorian tea factory perched at 2,200m — extraordinary views over rolling tea estates.', facilities: ['Tea museum', 'Steam Spa', 'Fireplace Lounge', 'Tea Walks'], img: IMG.heritance },
  { name: 'Amaya Hills Kandy', stars: 4, tier: 'Resort', price: '$150/night', location: 'Kandy', desc: 'Hillside retreat overlooking Kandy with traditional architecture and lush garden terraces.', facilities: ['Infinity Pool', 'Ayurveda Spa', 'Cultural Shows', 'Garden Walks'], img: IMG.amaya},
  { name: 'The Villa Bentota by KK Collection', stars: 5, tier: 'Villa', price: '$200/night', location: 'Bentota', desc: 'Private luxury beach villa with butler service, plunge pool and direct access to Bentota beach.', facilities: ['Private Pool', 'Butler', 'Beach Access', 'Sunset Dining'], img: IMG.bentota },
];

const GALLERY_ITEMS = [
  { src: IMG.train, cat: 'Nature', caption: 'Nine Arch Bridge, Ella' },
  { src: IMG.perahera, cat: 'Culture', caption: 'Kandy Esala Perahera Festival' },
  { src: IMG.beach, cat: 'Beaches', caption: 'Southern Coastline' },
  { src: IMG.tea2, cat: 'Nature', caption: 'Tea Plantations, Nuwara Eliya' },
  { src: IMG.elephant, cat: 'Wildlife', caption: 'Elephant, Udawalawe' },
  { src: IMG.galle, cat: 'Culture', caption: 'Galle Fort' },
  { src: IMG.adamspeak, cat: 'Culture', caption: 'Adam\'s Peak - Night View' },
  { src: IMG.beach2, cat: 'Beaches', caption: 'Mirissa Beach' },
  { src: IMG.sigiriyaAerial, cat: 'Nature', caption: 'Sigiriya — Aerial View' },
  { src: IMG.tea1, cat: 'Nature', caption: 'Tea Pickers, Hill Country' },
  { src: IMG.food, cat: 'Food', caption: 'Lamprais' },
  { src: IMG.elephant2, cat: 'Wildlife', caption: 'Wild Elephant' },
  { src: IMG.train2, cat: 'Nature', caption: 'Hill Country Train Journey' },
  { src: IMG.kandy, cat: 'Culture', caption: 'Temple of the Tooth' },
  { src: IMG.bird, cat: 'Wildlife', caption: 'Indian paradise flycatcher' },
  { src: IMG.rice, cat: 'Food', caption: 'Traditional Rice & Curry' },
  { src: IMG.surf, cat: 'Beaches', caption: 'Surfing' },
  { src: IMG.traditional, cat: 'Food', caption: 'New Year Desserts' },
  { src: IMG.leopard, cat: 'Wildlife', caption: 'Leopard in Yala National Park' },
  { src: IMG.turtle, cat: 'Wildlife', caption: 'Turtle' },
  { src: IMG.batik, cat: 'Culture', caption: 'Batik Textiles Art' },
  { src: IMG.sigiriya, cat: 'Culture', caption: 'Sigiriya Rock Fortress' },
  { src: IMG.vesak, cat: 'Culture', caption: 'Vesak Lantern' },
  { src: IMG.woodCarving, cat: 'Culture', caption: 'Wood Carving' },
  { src: IMG.waterfall, cat: 'Nature', caption: 'St.Clair\'s Falls' },
  { src: IMG.bear, cat: 'Wildlife', caption: 'Sloth Bear' },
];

const BLOG_POSTS = [
  { title: 'Top 10 Beaches in Sri Lanka You Must Visit', author: 'Amali Perera', date: 'June 12, 2026', time: '8 min read', tags: ['Beaches', 'Travel'], img: IMG.beach, excerpt: 'From the golden sands of Mirissa to the windswept breaks of Arugam Bay, we rank Sri Lanka\'s most spectacular coastlines.' },
  { title: 'The Ultimate Backpacking Guide to Sri Lanka', author: 'Kasun Fernando', date: 'May 28, 2026', time: '12 min read', tags: ['Budget Travel', 'Backpacking'], img: IMG.backpack, excerpt: 'How to explore Sri Lanka on $30 per day — the best cheap eats, guesthouses and transport tips.' },
  { title: 'Best Time to Visit Sri Lanka: Month by Month', author: 'Nishani De Silva', date: 'May 15, 2026', time: '6 min read', tags: ['Planning', 'Weather'], img: IMG.tea2, excerpt: 'Sri Lanka\'s two monsoon seasons mean the best time to visit depends on which coast you plan to explore.' },
  { title: 'Hidden Gems: 7 Places Tourists Often Miss', author: 'Ravi Jayasinghe', date: 'April 30, 2026', time: '10 min read', tags: ['Hidden Gems', 'Local Tips'], img: IMG.hidden, excerpt: 'Skip the crowds and discover Ritigala, Buduruwagala and Knuckles Mountain Range — Sri Lanka\'s best-kept secrets.' },
  { title: 'Sri Lanka Photography Guide: Iconic Shots', author: 'Malith Weerasinghe', date: 'April 18, 2026', time: '9 min read', tags: ['Photography', 'Travel'], img: IMG.photography, excerpt: 'Golden hour at Sigiriya, misty Ella mornings and Galle Fort sunsets — the definitive photography locations.' },
  { title: 'Sri Lanka with Kids: A Family Travel Guide', author: 'Chathuri Ekanayake', date: 'April 5, 2026', time: '7 min read', tags: ['Family', 'Kids'], img: IMG.family, excerpt: 'Elephant encounters, beach days and cultural experiences that children love — Sri Lanka is a fantastic family destination.' },
  { title: 'Solo Travel in Sri Lanka: Safety & Tips', author: 'Amali Perera', date: 'March 22, 2026', time: '8 min read', tags: ['Solo Travel', 'Safety'], img: IMG.solo, excerpt: 'Sri Lanka is one of Asia\'s safest destinations for solo travelers. Here\'s everything you need to know before going alone.' },
  { title: 'Sri Lanka Budget Travel: $25/Day Itinerary', author: 'Kasun Fernando', date: 'March 10, 2026', time: '11 min read', tags: ['Budget', 'Itinerary'], img: IMG.budget, excerpt: 'Proof that Sri Lanka is affordable: our detailed day-by-day budget itinerary covering food, transport and accommodation.' },
];

const FAQS = [
  { q: 'Do I need a visa to visit Sri Lanka?', a: 'Most nationalities require an Electronic Travel Authorization (ETA). Apply online at eta.gov.lk before departure. Costs approximately $35–50 USD and is usually approved within minutes.' },
  { q: 'What is the best way to get around Sri Lanka?', a: 'Trains are scenic and affordable for long distances (especially the hill country route). Tuk-tuks for short hops. Private drivers with car are recommended for comfort. Buses are cheap but crowded.' },
  { q: 'What currency is used in Sri Lanka?', a: 'Sri Lankan Rupee (LKR). USD and EUR are accepted in tourist areas. ATMs are widely available in cities and most tourist towns. Credit cards accepted at hotels and restaurants.' },
  { q: 'Is Sri Lanka safe for tourists?', a: 'Yes, Sri Lanka is generally very safe for tourists. The country is welcoming and peaceful. Exercise standard travel precautions, avoid unmarked beach areas at night and be cautious during swimming in strong surf.' },
  { q: 'Is there internet access throughout Sri Lanka?', a: '4G internet coverage is available across most of the island. Buy a local SIM card (Dialog or Mobitel) at the airport for affordable data. Most hotels and cafés offer free Wi-Fi.' },
];
